"""empty message

Revision ID: 4f1ff116a601
Revises: 6c8469c9964e
Create Date: 2021-04-28 01:37:01.967547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1ff116a601'
down_revision = '6c8469c9964e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'postnewsdb', ['id'])
    op.create_unique_constraint(None, 'postnewslogdb', ['id'])
    op.add_column('userdb', sa.Column('alias', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'userdb', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userdb', type_='unique')
    op.drop_column('userdb', 'alias')
    op.drop_constraint(None, 'postnewslogdb', type_='unique')
    op.drop_constraint(None, 'postnewsdb', type_='unique')
    # ### end Alembic commands ###
