"""empty message

Revision ID: 8eb58e0772cd
Revises: a715086dad0f
Create Date: 2021-05-10 22:41:10.514237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb58e0772cd'
down_revision = 'a715086dad0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdb', sa.Column('code_recovery', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdb', 'code_recovery')
    # ### end Alembic commands ###
