"""empty message

Revision ID: a715086dad0f
Revises: 4f1ff116a601
Create Date: 2021-05-01 22:27:15.406911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a715086dad0f'
down_revision = '4f1ff116a601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('postnewsdb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('type_file', sa.String(length=256), nullable=True),
    sa.Column('sleep', sa.Integer(), nullable=True),
    sa.Column('screen', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['userdb.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name'),
    sa.UniqueConstraint('id')
    )
    op.create_table('postnewslogdb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['userdb.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postnewslogdb')
    op.drop_table('postnewsdb')
    op.drop_table('userdb')
    # ### end Alembic commands ###
